### ISSUE TITLE
启动后没有吃GPU，运行速度也很慢，是怎么回事呢

### ISSUE THREAD

**Issue by maudBoy** [thu-coai/CharacterGLM-6B#21]
### System Info / 系統信息

CUDA 10020，py 3.10

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

/.conda/envs/py310/lib/python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)

### Expected behavior / 期待表现

怎么样可以加速分析呢

**Comment by zRzRzRzRzRzRzR** [comment]
走了CPU了吧，你这个不是已经cuda报错了，驱动版本不够

**Comment by maudBoy** [comment]
> 走了CPU了吧，你这个不是已经cuda报错了，驱动版本不够
已经解决了，是驱动版本的问题，走CPU了
